export interface Recommendation {
  scan_date: string;
  ticker: string;
  company_name: string | null;
  industry: string | null;
  price: number | null;
  entry_price: number | null;
  stop_loss: number | null;
  exit_price: number | null;
  upside_pct: number | null;
  risk_reward: number | null;
  current_rsi: number | null;
  volume_ratio: number | null;
  score: number | null;
  regime: string | null;
  past_win_rate?: number | null;
  expectancy_pct?: number | null;
  total_trades?: number | null;
  wins?: number | null;
  losses?: number | null;
  composite_score: number | null;
  tier_label: string | null;
  adx_value: number | null;
  macd_histogram: number | null;
  rsi_min_10d: number | null;
  ema20: number | null;
  is_fallback: boolean | null;
  is_momentum_exception: boolean | null;
  distance_from_high_pct: number | null;
  target_1?: number | null;
  target_2?: number | null;
  target_3?: number | null;
  target_1_pct?: number | null;
  target_2_pct?: number | null;
  target_3_pct?: number | null;
  weighted_rr?: number | null;
  position_sizing?: string | null;
  allocated_dollars?: number | null;
  max_shares?: number | null;
  narrative?: string | null;
  strategy?: string | null;
  strategy_name?: string | null;
  quality_score?: number | null;
  context_score?: number | null;
  entry_date?: string | null;
  exit_date?: string | null;
  status?: string | null;
  sell_signal?: boolean | null;
  sell_signal_reason?: string | null;
  sell_price?: number | null;
  context_analyst?: number | null;
  context_earnings?: number | null;
  context_news?: number | null;
  context_fundamental?: number | null;
}

export interface ScanLog {
  scan_date: string;
  tickers_scanned: number;
  signals_generated: number;
  signals_qualified?: number;
  signals_recommended?: number;
  scan_duration_secs: number;
  status: string;
  error_message: string | null;
  regime?: string;
  active_strategies?: number;
  skipped_strategies?: Record<string, string>;
  rsi_breadth_pct?: number;
}
